DROP TABLE IF EXISTS djS0rrow_review CASCADE;
DROP TABLE IF EXISTS djS0rrow_orderitem CASCADE;
DROP TABLE IF EXISTS djS0rrow_order CASCADE;
DROP TABLE IF EXISTS djS0rrow_customer CASCADE;
DROP TABLE IF EXISTS djS0rrow_clothes_collection CASCADE;
DROP TABLE IF EXISTS djS0rrow_clothes CASCADE;
DROP TABLE IF EXISTS djS0rrow_brand CASCADE;
DROP TABLE IF EXISTS djS0rrow_collection CASCADE;
DROP TABLE IF EXISTS djS0rrow_category CASCADE;

CREATE TABLE IF NOT EXISTS djS0rrow_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS djS0rrow_collection (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    season      VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS djS0rrow_brand (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    country     VARCHAR(255),
    logo        VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS djS0rrow_clothes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    price        DOUBLE PRECISION NOT NULL,
    size         VARCHAR(10) NOT NULL DEFAULT '36',
    color        VARCHAR(255) NOT NULL,
    photo        VARCHAR(100),
    create_date  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_exists    BOOLEAN NOT NULL DEFAULT TRUE,
    category_id  BIGINT NOT NULL,
    brand_id     BIGINT,
    CONSTRAINT fk_clothes_category
        FOREIGN KEY (category_id) REFERENCES djS0rrow_category (id),
    CONSTRAINT fk_clothes_brand
        FOREIGN KEY (brand_id) REFERENCES djS0rrow_brand (id)
);

CREATE TABLE IF NOT EXISTS djS0rrow_clothes_collection (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clothes_id    BIGINT NOT NULL,
    collection_id BIGINT NOT NULL,
    CONSTRAINT fk_clothes_collection_clothes
        FOREIGN KEY (clothes_id) REFERENCES djS0rrow_clothes (id),
    CONSTRAINT fk_clothes_collection_collection
        FOREIGN KEY (collection_id) REFERENCES djS0rrow_collection (id),
    CONSTRAINT uniq_clothes_collection UNIQUE (clothes_id, collection_id)
);

CREATE TABLE IF NOT EXISTS auth_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(150) NOT NULL UNIQUE,
    password     VARCHAR(128) NOT NULL,
    email        VARCHAR(254),
    first_name   VARCHAR(150),
    last_name    VARCHAR(150),
    is_staff     BOOLEAN NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS djS0rrow_customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(254) NOT NULL,
    phone      VARCHAR(20),
    CONSTRAINT fk_customer_user
        FOREIGN KEY (user_id) REFERENCES auth_user (id)
);

CREATE TABLE IF NOT EXISTS djS0rrow_order (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    customer_id  BIGINT NOT NULL,
    order_date   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status       VARCHAR(20) NOT NULL DEFAULT 'new',
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id) REFERENCES auth_user (id),
    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id) REFERENCES djS0rrow_customer (id)
);

CREATE TABLE IF NOT EXISTS djS0rrow_orderitem (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL,
    clothes_id     BIGINT NOT NULL,
    quantity       INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1),
    price_at_order DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_orderitem_order
        FOREIGN KEY (order_id) REFERENCES djS0rrow_order (id),
    CONSTRAINT fk_orderitem_clothes
        FOREIGN KEY (clothes_id) REFERENCES djS0rrow_clothes (id)
);

CREATE TABLE IF NOT EXISTS djS0rrow_review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clothes_id  BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    rating      SMALLINT NOT NULL CHECK (rating >= 0),
    text        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_review_clothes
        FOREIGN KEY (clothes_id) REFERENCES djS0rrow_clothes (id),
    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id) REFERENCES djS0rrow_customer (id)
);

