from django.urls import path

from .views import (
    BrandCreateView,
    BrandDeleteView,
    BrandDetailView,
    BrandListView,
    BrandUpdateView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryDetailView,
    CategoryListView,
    CategoryUpdateView,
    ClothesCreateView,
    ClothesDeleteView,
    ClothesDetailView,
    ClothesListView,
    ClothesUpdateView,
    CollectionCreateView,
    CollectionDeleteView,
    CollectionDetailView,
    CollectionListView,
    CollectionUpdateView,
    CustomerCreateView,
    login_view,
    logout_view,
    CustomerDeleteView,
    CustomerDetailView,
    CustomerListView,
    CustomerUpdateView,
    OrderCreateView,
    OrderDeleteView,
    OrderDetailView,
    OrderItemCreateView,
    OrderItemDeleteView,
    OrderItemDetailView,
    OrderItemListView,
    OrderItemUpdateView,
    OrderListView,
    OrderUpdateView,
    register_view,
    ReviewCreateView,
    ReviewDeleteView,
    ReviewDetailView,
    ReviewListView,
    ReviewUpdateView,
    home_view,
    info_view,
)


urlpatterns = [
    path('', home_view, name='home'),
    path('info/', info_view, name='info_view'),
    path('products/', ClothesListView.as_view(), name='product_list'),
    path('products/add/', ClothesCreateView.as_view(), name='product_add'),
    path('products/<int:pk>/', ClothesDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/edit/', ClothesUpdateView.as_view(), name='product_edit'),
    path('products/<int:pk>/delete/', ClothesDeleteView.as_view(), name='product_delete'),
    path('auth/login/', login_view, name='login'),
    path('auth/register/', register_view, name='register'),
    path('auth/logout/', logout_view, name='logout'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/add/', CategoryCreateView.as_view(), name='category_add'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('collections/', CollectionListView.as_view(), name='collection_list'),
    path('collections/add/', CollectionCreateView.as_view(), name='collection_add'),
    path('collections/<int:pk>/', CollectionDetailView.as_view(), name='collection_detail'),
    path('collections/<int:pk>/edit/', CollectionUpdateView.as_view(), name='collection_edit'),
    path('collections/<int:pk>/delete/', CollectionDeleteView.as_view(), name='collection_delete'),
    path('brands/', BrandListView.as_view(), name='brand_list'),
    path('brands/add/', BrandCreateView.as_view(), name='brand_add'),
    path('brands/<int:pk>/', BrandDetailView.as_view(), name='brand_detail'),
    path('brands/<int:pk>/edit/', BrandUpdateView.as_view(), name='brand_edit'),
    path('brands/<int:pk>/delete/', BrandDeleteView.as_view(), name='brand_delete'),
    path('customers/', CustomerListView.as_view(), name='customer_list'),
    path('customers/add/', CustomerCreateView.as_view(), name='customer_add'),
    path('customers/<int:pk>/', CustomerDetailView.as_view(), name='customer_detail'),
    path('customers/<int:pk>/edit/', CustomerUpdateView.as_view(), name='customer_edit'),
    path('customers/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/add/', OrderCreateView.as_view(), name='order_add'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/<int:pk>/edit/', OrderUpdateView.as_view(), name='order_edit'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('order-items/', OrderItemListView.as_view(), name='order_item_list'),
    path('order-items/add/', OrderItemCreateView.as_view(), name='order_item_add'),
    path('order-items/<int:pk>/', OrderItemDetailView.as_view(), name='order_item_detail'),
    path('order-items/<int:pk>/edit/', OrderItemUpdateView.as_view(), name='order_item_edit'),
    path('order-items/<int:pk>/delete/', OrderItemDeleteView.as_view(), name='order_item_delete'),
    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('reviews/add/', ReviewCreateView.as_view(), name='review_add'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('reviews/<int:pk>/edit/', ReviewUpdateView.as_view(), name='review_edit'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]
