# Generated by Django 6.0.5 on 2026-05-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категоря",
                "verbose_name_plural": "Категория",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категоря",
                "verbose_name_plural": "Категория",
            },
        ),
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование одежды"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание одежды"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "size",
                    models.PositiveIntegerField(default=36, verbose_name="Размер"),
                ),
                ("color", models.CharField(max_length=255, verbose_name="Цвет ")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/$Y/$m/$d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добалвения"
                    ),
                ),
                (
                    "is_exists",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="djS0rrow.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        to="djS0rrow.collection", verbose_name="Коллекция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция одежды",
                "verbose_name_plural": "Позиции одежды",
            },
        ),
    ]
