-- Физическая схема (DDL) по миграциям Django
-- Источник: python manage.py sqlmigrate djS0rrow 0001 и 0002

BEGIN;

-- 0001_initial
CREATE TABLE "djS0rrow_category" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text NULL
);

CREATE TABLE "djS0rrow_collection" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text NULL
);

CREATE TABLE "djS0rrow_clothes" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text NULL,
  "price" double precision NOT NULL,
  "size" integer NOT NULL CHECK ("size" >= 0),
  "color" varchar(255) NOT NULL,
  "photo" varchar(100) NULL,
  "create_date" timestamp with time zone NOT NULL,
  "is_exists" boolean NOT NULL,
  "category_id" bigint NOT NULL
);

CREATE TABLE "djS0rrow_clothes_collection" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "clothes_id" bigint NOT NULL,
  "collection_id" bigint NOT NULL
);

ALTER TABLE "djS0rrow_clothes"
  ADD CONSTRAINT "djS0rrow_clothes_category_id_b19603bd_fk_djS0rrow_category_id"
  FOREIGN KEY ("category_id") REFERENCES "djS0rrow_category" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "djS0rrow_clothes_category_id_b19603bd" ON "djS0rrow_clothes" ("category_id");

ALTER TABLE "djS0rrow_clothes_collection"
  ADD CONSTRAINT "djS0rrow_clothes_collect_clothes_id_collection_id_8d9f1615_uniq"
  UNIQUE ("clothes_id", "collection_id");

ALTER TABLE "djS0rrow_clothes_collection"
  ADD CONSTRAINT "djS0rrow_clothes_col_clothes_id_4031085b_fk_djS0rrow_"
  FOREIGN KEY ("clothes_id") REFERENCES "djS0rrow_clothes" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "djS0rrow_clothes_collection"
  ADD CONSTRAINT "djS0rrow_clothes_col_collection_id_32559a29_fk_djS0rrow_"
  FOREIGN KEY ("collection_id") REFERENCES "djS0rrow_collection" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "djS0rrow_clothes_collection_clothes_id_4031085b" ON "djS0rrow_clothes_collection" ("clothes_id");
CREATE INDEX "djS0rrow_clothes_collection_collection_id_32559a29" ON "djS0rrow_clothes_collection" ("collection_id");


-- 0002_brand_customer_alter_category_options_and_more
CREATE TABLE "djS0rrow_brand" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" text NULL,
  "country" varchar(255) NULL,
  "logo" varchar(100) NULL
);

CREATE TABLE "djS0rrow_customer" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "email" varchar(254) NOT NULL,
  "phone" varchar(20) NULL
);

ALTER TABLE "djS0rrow_collection" ADD COLUMN "season" varchar(100) NULL;

ALTER TABLE "djS0rrow_clothes"
  ADD COLUMN "brand_id" bigint NULL
  CONSTRAINT "djS0rrow_clothes_brand_id_a1f7a687_fk_djS0rrow_brand_id"
  REFERENCES "djS0rrow_brand"("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "djS0rrow_order" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "order_date" timestamp with time zone NOT NULL,
  "status" varchar(20) NOT NULL,
  "total_amount" double precision NOT NULL,
  "customer_id" bigint NOT NULL
);

CREATE TABLE "djS0rrow_orderitem" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "quantity" integer NOT NULL CHECK ("quantity" >= 0),
  "price_at_order" double precision NOT NULL,
  "clothes_id" bigint NOT NULL,
  "order_id" bigint NOT NULL
);

CREATE TABLE "djS0rrow_review" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "rating" smallint NOT NULL CHECK ("rating" >= 0),
  "text" text NULL,
  "created_at" timestamp with time zone NOT NULL,
  "clothes_id" bigint NOT NULL,
  "customer_id" bigint NOT NULL
);

CREATE INDEX "djS0rrow_clothes_brand_id_a1f7a687" ON "djS0rrow_clothes" ("brand_id");

ALTER TABLE "djS0rrow_order"
  ADD CONSTRAINT "djS0rrow_order_customer_id_330e614c_fk_djS0rrow_customer_id"
  FOREIGN KEY ("customer_id") REFERENCES "djS0rrow_customer" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "djS0rrow_order_customer_id_330e614c" ON "djS0rrow_order" ("customer_id");

ALTER TABLE "djS0rrow_orderitem"
  ADD CONSTRAINT "djS0rrow_orderitem_clothes_id_d35b4bce_fk_djS0rrow_clothes_id"
  FOREIGN KEY ("clothes_id") REFERENCES "djS0rrow_clothes" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "djS0rrow_orderitem"
  ADD CONSTRAINT "djS0rrow_orderitem_order_id_035563ea_fk_djS0rrow_order_id"
  FOREIGN KEY ("order_id") REFERENCES "djS0rrow_order" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "djS0rrow_orderitem_clothes_id_d35b4bce" ON "djS0rrow_orderitem" ("clothes_id");
CREATE INDEX "djS0rrow_orderitem_order_id_035563ea" ON "djS0rrow_orderitem" ("order_id");

ALTER TABLE "djS0rrow_review"
  ADD CONSTRAINT "djS0rrow_review_clothes_id_790e5cbc_fk_djS0rrow_clothes_id"
  FOREIGN KEY ("clothes_id") REFERENCES "djS0rrow_clothes" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "djS0rrow_review"
  ADD CONSTRAINT "djS0rrow_review_customer_id_8d4c28ef_fk_djS0rrow_customer_id"
  FOREIGN KEY ("customer_id") REFERENCES "djS0rrow_customer" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "djS0rrow_review_clothes_id_790e5cbc" ON "djS0rrow_review" ("clothes_id");
CREATE INDEX "djS0rrow_review_customer_id_8d4c28ef" ON "djS0rrow_review" ("customer_id");

COMMIT;

